### ISSUE TITLE
Media driver fails to compile with Onyx 0.9.15

### ISSUE THREAD

**Issue by neverfox** [onyx-platform/lib-onyx#13]
The bump to aeron 1.0.4 causes this to fail to compile:

```
java.lang.ClassNotFoundException: uk.co.real_logic.aeron.Aeron$Context, compiling:(media_driver.clj:1:1)
Exception in thread "main" java.lang.ClassNotFoundException: uk.co.real_logic.aeron.Aeron$Context, compiling:(media_driver.clj:1:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler.compile1(Compiler.java:7474)
	at clojure.lang.Compiler.compile1(Compiler.java:7464)
	at clojure.lang.Compiler.compile(Compiler.java:7541)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$compile$fn__5682.invoke(core.clj:5903)
	at clojure.core$compile.invokeStatic(core.clj:5903)
	at clojure.core$compile.invoke(core.clj:5895)
	at user$eval22$fn__31.invoke(form-init274841129574918731.clj:1)
	at user$eval22.invokeStatic(form-init274841129574918731.clj:1)
	at user$eval22.invoke(form-init274841129574918731.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
```

Also the latest version of this on clojars is 0.9.10.0. Is this library still considered relevant or is there a new preferred way to launch the media driver instead of `lib_onyx.media_driver`?

**Comment by neverfox** [comment]
I think I answered my last question seeing `aeron_media_driver.clj` in the main Onyx repo. Guess it's time to get with the times.

**Comment by lbradstreet** [comment]
Fixed now
